# This is the configuration file for Decap CMS.
# It should be placed in your site's `static/admin/` folder.
# Set localization for CMS dashboard only:
locale: "ru"
# Set localization i18n

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  structure:
    multiple_folders
    # Required - a list of locales to show in the editor UI
  locales:
    ["ru", "uz"]
    # Optional, defaults to the first item in locales.
    # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: "ru"

backend:
  name: git-gateway
  branch: main
  squash_merges: true

# The `media_folder` is the path where uploaded media will be saved, relative to the repository root.
# The `public_folder` is the path that will be used in the final front matter for the image URL.
media_folder: "static/images/uploads"
public_folder: "/images"

# Enables editorial workflow, which allows for drafts and reviews before publishing.
publish_mode: editorial_workflow

# Easy to access url to return main site
display_url: https://zarifboyev.space
# Custom logo for dashboard
logo_url: https://zarifboyev.space/images/logo.svg
# Keep search disabled in dashboard to optimize workflow
search: false

# Configures an external media library.
media_library:
  name: uploadcare
  config:
    publicKey: 28d536105b790be0d234
    max_file_size: 10000000 # 10 megabytes

# Defines a custom slug format.
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

  # These are the fields that will appear in the editor for each post.
  # This section defines the content collections for your site.
collections:
  - name: "posts"
    label: "Блог Посты" # Blog Posts
    folder: "content/{{locale}}/posts"
    i18n: true # This enables the multilingual UI for this collection
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    editor:
      preview: true # Enables the live preview pane for this collection.

    fields:
      - label: Заголовок
        name: title
        widget: string
        i18n: true
      - label: Описание
        name: description
        widget: string
        i18n: true
      - label: Дата
        name: date
        widget: datetime
        i18n: duplicate

  # # You can add other collections here, e.g., for single pages like "About Us"
  # - name: "pages"
  #   label: "Страницы"
  #   folder: "content/{{locale}}/pages"
  #   i18n: true
  #   create: true
  #   editor:
  #     preview: false
  #   fields:
  #     - { label: "Заголовок", name: "title", widget: "string", i18n: true }
  #     - {
  #         label: "Тело страницы",
  #         name: "body",
  #         widget: "markdown",
  #         i18n: true,
  #       }
  #     - {
  #         label: "Черновик?",
  #         name: "draft",
  #         widget: "boolean",
  #         default: false,
  #         i18n: "duplicate",
  #       }
